def main():
    while True:
        print("\n1. Hexadecimal to Decimal")
        print("2. Hexadecimal to Octal")
        print("3. Hexadecimal to Binary")
        print("4. Decimal to Hexadecimal")
        print("5. Decimal to Octal")
        print("6. Decimal to Binary")
        print("7. Octal to Decimal")
        print("8. Octal to Hexadecimal")
        print("9. Octal to Binary")
        print("10. Binary to Decimal")
        print("11. Binary to Hexadecimal")
        print("12. Binary to Octal")
        print("13. Exit")